// ======== START AUTH SECTION ========
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'
export const LOG_OUT = 'LOG_OUT'
export const USER_AUTHENTICATED = 'LOG_IN_CHECK_SUCCESS'
export const USER_NOT_AUTHENTICATED = 'LOG_IN_CHECK_ERROR'
// ======== END AUTH SECTION ========

export const REDIRECT_CHANGE_URL = 'REDIRECT_CHANGE_URL'

// ======== START UI SECTION ========
export const LOADING_LAYER_ENABLED = 'LOADING_LAYER_ENABLED'
export const LOADING_LAYER_DISABLED = 'LOADING_LAYER_DISABLED'

export const HIDE_AUTH_LAYER = 'HIDE_REGISTER_LOGIN_LAYER'
export const SHOW_AUTH_LAYER = 'SHOW_REGISTER_LOGIN_LAYER'
// ======== END SECTION ========

// ======== START INFO SECTION ========
export const SHOW_ERROR_LAYER = 'SHOW_ERROR_LAYER'
export const HIDE_ERROR_LAYER = 'HIDE_ERROR_LAYER'

export const SHOW_MESSAGE_LAYER = 'SHOW_MESSAGE_LAYER'
export const HIDE_MESSAGE_LAYER = 'HIDE_MESSAGE_LAYER'
// ======== END INFO SECTION ========

// ======== START POKEMONS SECTION ========
export const GET_POKEMONS = 'GET_POKEMONS'
export const GET_FAVOURITE_POKEMONS = 'GET_FAVOURITE_POKEMONS'
export const ADD_FAVOURITE_POKEMON = 'ADD_FAVOURITE_POKEMON'
export const REMOVE_FAVOURITE_POKEMON = 'REMOVE_FAVOURITE_POKEMON'
export const CHANGE_POKEMON_PAGINATION_AMOUNT = 'CHANGE_POKEMON_PAGINATION_AMOUNT'
export const CHANGE_POKEMON_PAGINATION_PAGE_NUMBER = 'CHANGE_POKEMON_PAGINATION_PAGE_NUMBER'
export const SEARCH_INPUT_CHANGE = 'SEARCH_INPUT_CHANGE'
export const SET_TOTAL_COUNT_PAGINATION = 'SET_TOTAL_COUNT_PAGINATION'
// ======== END POKEMONS SECTION ========
